# Configuration for running a full Sigil sequencer in the event the centralized Sigil sequencer is down.

services:
  op-node:
    entrypoint: /scripts/exit/start-op-node.sh

  op-geth:
    entrypoint: /scripts/exit/start-op-geth.sh

  op-succinct-validity:
    # Succinct doesn't have a public image repository so we hosted our own image.
    # You're welcome to build your own and use it here instead: github.com/succinctlabs/op-succinct/tree/v2.3.0
    image: jossduff/op-succinct-validity:v2.3.0
    entrypoint: /scripts/exit/start-op-succinct-validity.sh
    env_file:
      # default values
      - .env.default
      # Maintainer set values like contract addresses, chain ids, etc
      - .env.maintainer
      # Values required to be set by end user like private key, rpcs, and api keys
      - .env
    volumes:
      - ./scripts:/scripts
      # op-succinct-validity expects the up-to-date `configs/51611.json` at this location 
      # in the container
      - ./config:/app/configs
      - validity-tmp:/tmp
    ports:
      - ${PORT__OP_SUCCINCT_VALIDITY_HTTP}:${PORT__OP_SUCCINCT_VALIDITY_HTTP}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - L1_RPC=${L1_RPC_URL}
      - L1_BEACON_RPC=${L1_BEACON_RPC_URL}
      - L2_RPC=http://op-geth:8545
      - L2_NODE_RPC=http://op-node:9545
      # use the OP_SUCCINCT_DATABASE_URL if provided, otherwise use the local postgres db container
      - DATABASE_URL=${OP_SUCCINCT_VALIDITY_DATABASE_URL}
      - NETWORK_RPC_URL=http://hierophant:${PORT__HIEROPHANT_GRPC}
      # How many provers working concurrently.  This should be the same as magister's NUMBER_INSTANCES
      - MAX_CONCURRENT_PROOF_REQUESTS=${NUMBER_PROVERS}
    depends_on:
      - postgres
      - op-geth
      - op-node
      - hierophant
      - magister
    restart: unless-stopped

  # Used to store proof requests for op-succinct-validity
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-succinct
      POSTGRES_DB: op-succinct
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # locally hosted prover network
  hierophant:
    # You're welcome to build your own image and use it here instead: https://github.com/unattended-backpack/hierophant/
    image: jossduff/hierophant:latest
    entrypoint: /scripts/exit/start-hierophant.sh
    env_file:
      # default values
      - .env.default
      # Maintainer set values like contract addresses, chain ids, etc
      - .env.maintainer
      # Values required to be set by end user like private key, rpcs, and api keys
      - .env
    volumes:
      - ./scripts:/scripts
    ports:
      - ${PORT__HIEROPHANT_HTTP}:${PORT__HIEROPHANT_HTTP}
      - ${PORT__HIEROPHANT_GRPC}:${PORT__HIEROPHANT_GRPC}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # manages worker nodes who execute proofs for Hierophant
  magister:
    # You're welcome to build your own image and use it here instead: https://github.com/unattended-backpack/magister
    image: jossduff/magister:latest
    entrypoint: /scripts/exit/start-magister.sh
    env_file:
      # default values
      - .env.default
      # Maintainer set values like contract addresses, chain ids, etc
      - .env.maintainer
      # Values required to be set by end user like private key, rpcs, and api keys
      - .env
    volumes:
      - ./scripts:/scripts
    ports:
      - ${PORT__MAGISTER_HTTP}:${PORT__MAGISTER_HTTP}
    environment:
      # Number of prover instances to run.  Should be the same as op-succinct-validity's MAX_CONCURRENT_PROOF_REQUESTS
      - NUMBER_INSTANCES=${NUMBER_PROVERS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - hierophant
    restart: unless-stopped

volumes:
  postgres-data:
  validity-tmp:
