# Configuration for running a full Sigil sequencer in the event the centralized
# Sigil sequencer is down.

services:
  op-node:
    entrypoint: /scripts/sequencer/start-op-geth.sh

  op-reth:
    entrypoint: /scripts/sequencer/start-op-reth.sh

  op-batcher:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.13.1
    restart: on-failure
    stop_grace_period: 5m
    entrypoint: /scripts/sequencer/start-op-batcher.sh
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
    ports:
      - ${PORT__OP_BATCHER_HTTP: -8548}:8548
    extra_hosts:
      - "host.docker.internal:host-gateway"

  op-succinct-validity:
    # Succinct doesn't have a public image repository so we built our own for now.
    # You're welcome to build your own and use it here instead github.com/succinctlabs/op-succinct/
    image: jossduff/op-succinct-validity:latest
    env_file:
      - .env
    volumes:
      - ./scripts/:/scripts
    ports:
      - ${PORT__OP_SUCCINCT_VALIDITY_HTTP: -3001}:3001 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=postgres://op-succinct@postgres:5432/op-succinct
      - RUST_LOG_STYLE=always
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    depends_on:
      - postgres
    restart: unless-stopped

  # Used to store proof requests for op-succinct-validity
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-succinct
      POSTGRES_DB: op-succinct
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
