# Configuration for running a full Sigil sequencer in the event the centralized Sigil sequencer is down.

services:
  op-node:
    entrypoint: /scripts/sequencer/start-op-node.sh

  op-geth:
    entrypoint: /scripts/sequencer/start-op-geth.sh

  op-batcher:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.13.1
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/sequencer/start-op-batcher.sh
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      - shared:/shared
    ports:
      - ${PORT__OP_BATCHER_HTTP:-8548}:${PORT__OP_BATCHER_HTTP:-8548}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - op-geth
      - op-node

  op-succinct-validity:
    # Succinct doesn't have a public image repository so we hosted our own image.
    # You're welcome to build your own and use it here instead: github.com/succinctlabs/op-succinct/tree/v2.3.0
    image: jossduff/op-succinct-validity:v2.3.0
    entrypoint: /scripts/sequencer/start-op-succinct-validity.sh
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      # op-succinct-validity expects the up-to-date `configs/51611.json` at this location 
      # in the container
      - ./config:/app/configs
      - validity-tmp:/tmp
    ports:
      - ${PORT__OP_SUCCINCT_VALIDITY_HTTP:-3001}:${PORT__OP_SUCCINCT_VALIDITY_HTTP:-3001}:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - L1_RPC=${L1_RPC_URL}
      - L1_BEACON_RPC=${L1_BEACON_RPC_URL}
      - L2_RPC=http://op-geth:8545
      - L2_NODE_RPC=http://op-node:9545
      # use the OP_SUCCINCT_DATABASE_URL if provided, otherwise use the local postgres db container
      - DATABASE_URL=${OP_SUCCINCT_VALIDITY_DATABASE_URL:-postgres://op-succinct@postgres:5432/op-succinct}
      - RUST_LOG_STYLE=always
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    depends_on:
      - postgres
      - op-geth
      - op-node
    restart: unless-stopped

  # Used to store proof requests for op-succinct-validity
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-succinct
      POSTGRES_DB: op-succinct
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  validity-tmp:
