# Base configuration.  Not meant to be used by itself, use either
# docker-compose.node.yml or docker-compose.sequencer.yml as overrides

services:
  op-node: 
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.13.3
    restart: unless-stopped
    stop_grace_period: 5m
    env_file:
      - .env
    volumes:
      - ./config:/chainconfig
      - ./scripts:/scripts
      - shared:/shared
      - safedb:/safedb
    ports:
      - ${PORT__OP_NODE_P2P:-9222}:9222/udp
      - ${PORT__OP_NODE_P2P:-9222}:9222/tcp
      - ${PORT__OP_NODE_HTTP:-9545}:9545
      - 7300:7300
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      initialize:
        condition: service_completed_successfully

  op-geth: 
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101511.0
    restart: unless-stopped
    stop_grace_period: 5m
    env_file:
      - .env
    volumes:
      - ./config:/chainconfig
      - ./scripts:/scripts
      - shared:/shared
      - datadir:/datadir
    ports:
      - ${PORT__OP_GETH_HTTP:-8545}:8545
      - ${PORT__OP_GETH_WS:-8546}:8546
      - ${PORT__OP_GETH_P2P:-30303}:30303/udp
      - ${PORT__OP_GETH_P2P:-30303}:30303/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      initialize:
        condition: service_completed_successfully

  # initializes datadir and jwt.txt, then writes INITIALIZED.txt
  initialize:
    image: alpine:latest
    command: /bin/sh -c "apk add --no-cache openssl && /scripts/initialize.sh"
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      - shared:/shared
      - datadir:/datadir
    restart: "no"

volumes:
  datadir: # chain data
  shared: # for storing jwt.txt and INITIALIZED.txt
  safedb: # for op-node
